### ISSUE TITLE
How to understand "the hidden layer before the projection head is a better representation than the layer after"

### ISSUE THREAD

**Issue by byougert** [thunderInfy/simclr#3]
Thanks so much about your code and article(Understanding SimCLR — A Simple Framework for Contrastive Learning of Visual Representations with Code). But when reading the paper——A Simple Framework for Contrastive Learning of Visual Representations，I still have some puzzles in the paper 4.2(A nonlinear projection head), which says “even when nonlinear
projection is used, the layer before the projection head, h,is still much better (>10%) than the layer after, z = g(h),which shows that the hidden layer before the projection head is a better representation than the layer after.” In fact, the subsequent experiment verifies this hypothesis, but I wonder how to get this hypothesis from Figure 8, which exactly shows that "a nonlinear projection is better than a linear projection (+3%), and much better than no projection (>10%)".

**Comment by thunderInfy** [comment]
Hey, 

I think we can't get this hypothesis from Figure 8. Table 3 verifies this hypothesis as you already know. 

Fig. 8 as you know deals with another question that whether a non-linear projection is better than a linear projection or no projection at all. 

The reason we can't get this hypothesis from Fig. 8 is because, to get this hypothesis, we need to have the same model and the same projection head. But Fig. 8 deals with different projection heads.

**Comment by byougert** [comment]
many thanks.
