### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\train\\names.txt'

### ISSUE THREAD

**Issue by iumemon** [thunderInfy/simclr#4]
I am using the dataset (https://github.com/thunderInfy/imagenet-5-categories) prepared by you and getting the following error. I am confused about the function of this names.txt

(simclr) D:\Projects\simclr>python main.py dataset results
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    TrainDataset(args),
  File "main.py", line 29, in __init__
    with open(os.path.join(args.datapath, "train","names.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\train\\names.txt'

and If I am removing this names.txt from argument I am getting following error
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    TrainDataset(args),
  File "main.py", line 29, in __init__
    with open(os.path.join(args.datapath, "train")) as f:
PermissionError: [Errno 13] Permission denied: 'dataset\\train'

**Comment by thunderInfy** [comment]
Hey, please read the "Dataset" section in readme. The google drive link which is present there ([this link](https://drive.google.com/file/d/1x3BSoqoe76FcWdbagLj6Mx6_2EAJ982g/view?usp=sharing)), I have used that version of the dataset. 
The names.txt file just contains the names of all the files present in the train folder. It's not necessary to have that file actually, because we can just get the names from os listdir function.
